Repository nstrydom2/anonfile-api, pull requests merged in 2023-07, with the labels that each got.

#84 Update prod dependencies
  requirements/release.txt
Labels: bug

#85 Add default location for logger config
  src/anonfile/anonfile.py
Labels: bug

#86 Configure OS Matrix in Workflow File
  .github/workflows/python-package.yml
  requirements/release.txt
Labels: enhancement

#87 Update Changelog
  .github/workflows/python-publish.yml
  CHANGELOG.md
  README.md
  requirements/dev.txt
  requirements/release.txt
  src/anonfile/anonfile.py
Labels: enhancement, dependencies

#89 Refactor CLI code
  CHANGELOG.md
  README.md
  src/anonfile/__init__.py
Labels: enhancement
